/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-4': 'var(--surface-4)',
        hairline: 'var(--hairline)',
        'hairline-strong': 'var(--hairline-strong)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-focus': 'var(--primary-focus)',
        ink: 'var(--ink)',
        'ink-muted': 'var(--ink-muted)',
        'ink-subtle': 'var(--ink-subtle)',
        'ink-tertiary': 'var(--ink-tertiary)',
        success: 'var(--semantic-success)',
        'status-wishlist': 'var(--status-wishlist)',
        'status-applied': 'var(--status-applied)',
        'status-interview': 'var(--status-interview)',
        'status-offer': 'var(--status-offer)',
        'status-rejected': 'var(--status-rejected)',
      },
      fontFamily: {
        sans: ['Inter', 'SF Pro Display', '-apple-system', 'system-ui', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
      },
      letterSpacing: {
        'display-xl': '-0.1875rem',
        'display-lg': '-0.1125rem',
        'display-md': '-0.0625rem',
        headline: '-0.0375rem',
        'card-title': '-0.025rem',
        subhead: '-0.0125rem',
        'body-lg': '-0.00625rem',
        body: '-0.003125rem',
        eyebrow: '0.025rem',
      },
    },
  },
  plugins: [],
}
